# Travis CI config

sudo: false
language: node_js
matrix:
  include:
    - node_js: 0.10
    - node_js: 0.12
    - node_js: 4
    - node_js: 5
  branched:
    only:
      - master
      - /^PR /
before_script:
  - "npm run build"